Cen 34
CEN-Project-Group-2/Bookstore-API pull request #18
Opened 2023-07-07 02:58 UTC by Tajae1532

2023-07-07 03:09 UTC, eandrews737 submitted a review, later dismissed

2023-07-07 03:16 UTC, lamad019 approved these changes

2023-07-07 03:29 UTC, lamad019 submitted a review, later dismissed
Conflicting files removed, should be good now

2023-07-07 03:33 UTC, eandrews737 approved these changes

2023-07-09 14:12 UTC, eandrews737 requested changes

2023-07-09 14:12 UTC, eandrews737 commented on djangoBookStoreApi/urls.py
> +#h
```suggestion
```

2023-07-09 14:12 UTC, eandrews737 commented on djangoBookStoreApi/views/user_profile_view.py
> +        #h
```suggestion
```

2023-07-09 14:12 UTC, eandrews737 commented on djangoBookStoreApi/views/user_profile_view.py
> +        if username:
we need to make checks for if they have username and password at the beginning of this function

2023-07-09 16:52 UTC, closed without merging

2023-07-09 16:52 UTC, Tajae1532 commented
Will Close