CEN-49/50: Two Post Request and Get Fixes
CEN-Project-Group-2/Bookstore-API pull request #22
Opened 2023-07-09 18:44 UTC by lamad019

1. Add book POST request made. Multiple checks to avoid any errors.
2. Create new wishlist POST request made. Multiple checks to avoid any errors. Also accounted for a maximum of 3 wish lists per user.
3. Fixed the GET request to properly post book names for whatever wishlist ID was inputted.

2023-07-09 18:47 UTC, lamad019 commented
3*. Will later update the url path to take parameters rather than use the URL itself. Also will include checks to avoid any issues involving the wishlist id parameter.

2023-07-09 18:52 UTC, eandrews737 requested changes

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +    bookID = data.get('bookID')
```suggestion
    bookID = data.get('book_id')
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +    wishlistID = data.get('wishlistID')
```suggestion
    wishlistID = data.get('wish_list_id')
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Error' : 'BookID or WishlistID missing. Please enter it again.'
```suggestion
            'Error' : 'book_id or wish_list_id missing. Please enter it again.'
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Error' : 'BookID submitted does not exist within the database.'
```suggestion
            'Error' : 'book_id submitted does not exist within the database.'
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Error' : 'WishlistID submitted does not exist within the database.'
```suggestion
            'Error' : 'wish_list_id submitted does not exist within the database.'
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Message' : 'Book ID has been successfully added to associated Wishlist.',
```suggestion
            'Message' : 'Book has been successfully added to the associated wish list.',
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Book ID' : bookID,
```suggestion
            'book_id' : bookID,
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Wish List ID' : wishlistID
```suggestion
            'wish_list_id' : wishlistID
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Error' : 'User ID or Wishlist Name is missing. Please enter it again.'
```suggestion
            'Error' : 'user_id or wish_list_name is missing. Please enter it again.'
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +    wishlistName = data.get('wishlist_name')
```suggestion
    wishlistName = data.get('wish_list_name')
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'User ID' : userID,
```suggestion
            'user_id' : userID,
```

2023-07-09 18:52 UTC, eandrews737 commented on djangoBookStoreApi/views/wish_list_books_view.py
> +            'Wish List Name' : wishlistName
```suggestion
            'wish_list_name' : wishlistName
```

2023-07-09 18:59 UTC, lamad019 reviewed
changes made

2023-07-09 19:01 UTC, eandrews737 submitted a review, later dismissed

2023-07-16 17:04 UTC, eandrews737 approved these changes

2023-07-16 23:56 UTC, junior033 approved these changes

2023-07-16 23:56 UTC, merged