Cen-19: As a developer I need to make a table migration for the wish lists and wish list books table
CEN-Project-Group-2/Bookstore-API pull request #6
Opened 2023-06-07 01:15 UTC by lamad019

2023-06-07 01:17 UTC, eandrews737 requested changes

2023-06-07 01:17 UTC, eandrews737 commented on migrations/wish_lists_and_wish_lists_books_tables.sql
> +FOREIGN KEY (book_id) REFERENCES books(id)
```suggestion
  id int AUTO_INCREMENT PRIMARY KEY,
  wish_list_id int,
  book_id int,
  created_at date,
  deleted_at date,
  FOREIGN KEY (wish_list_id) REFERENCES wish_lists(id),
  FOREIGN KEY (book_id) REFERENCES books(id)
```

2023-06-07 01:17 UTC, eandrews737 commented on migrations/wish_lists_and_wish_lists_books_tables.sql
> +FOREIGN KEY (user_id) references users(id)
```suggestion
  id int AUTO_INCREMENT PRIMARY KEY,
  user_id int,
  FOREIGN KEY (user_id) references users(id)
```

2023-06-07 01:17 UTC, eandrews737 commented on migrations/wish_lists_and_wish_lists_books_tables.sql
> +create table wish_lists_books (
```suggestion
create table wish_list_books (
```

2023-06-07 01:18 UTC, eandrews737 approved these changes

2023-06-08 23:58 UTC, junior033 approved these changes

2023-06-08 23:58 UTC, merged