Cen 17
CEN-Project-Group-2/Bookstore-API pull request #7
Opened 2023-06-08 23:35 UTC by NicholasBelschner

2023-06-08 23:48 UTC, Tajae1532 approved these changes

2023-06-08 23:58 UTC, junior033 submitted a review, later dismissed

2023-06-08 23:59 UTC, eandrews737 requested changes

2023-06-08 23:59 UTC, eandrews737 commented on Migration/books_migration.sql
> +  deleted_at VARCHAR(50)
```suggestion
  created_at DATE,
  deleted_at DATE
```

2023-06-09 00:00 UTC, eandrews737 approved these changes

2023-06-09 00:01 UTC, junior033 approved these changes

2023-06-09 00:01 UTC, merged