added tables for rating and comments
CEN-Project-Group-2/Bookstore-API pull request #9
Opened 2023-06-08 23:56 UTC by junior033

2023-06-09 00:01 UTC, eandrews737 approved these changes

2023-06-11 00:51 UTC, lamad019 approved these changes

2023-06-11 04:41 UTC, eandrews737 commented
Do not merge this. It will have conflicts with the changes I made

2023-06-11 04:43 UTC, eandrews737 requested changes
Will cause a merge conflict

2023-06-28 01:03 UTC, closed without merging